### ISSUE TITLE
Using CombineFirebase in two targets in one workspace warning

### ISSUE THREAD

**Issue by pzmudzinski** [rever-ai/CombineFirebase#15]
I have app and internal framework which both use `CombineFirebase` package, something like:
```
target 'App' do
   pod 'CombineFirebase/Firestore'
end

target 'Framework' do
  pod 'CombineFirebase/Firestore'
end
```

Whenever I start the app I am getting this warning/error:

> objc[57881]: Class PodsDummy_CombineFirebaseFirestore is implemented in both /Users/piotr/Library/Developer/Xcode/DerivedData/App-dbwukpdmwlehcvgucgaodxjqjwty/Build/Products/Debug-iphonesimulator/Framework.framework/Framework (0x10629ce90) and /Users/piotr/Library/Developer/CoreSimulator/Devices/5E6D142F-38F6-46FA-96C6-78D9758B117B/data/Containers/Bundle/Application/8EADBC84-1081-4D49-9633-5AF1E4F16DFF/App.app/App (0x101973a28). One of the two will be used. Which one is undefined.

Not sure if it's some setting coming from the `CombineFirebase` or something I have to setup in `Podfile`.

**Comment by kshivang** [comment]
Using pod 'CombineFirebase/Firestore'  in any of two targets should be enough, it's more of Podfile setup.

**Comment by pzmudzinski** [comment]
Could we put more details here rather than "it's more of Podfile setup"?
It turned out I cannot archive my xcode project because of this issue with similar error message: 
`Multiple commands produce 'blablabla/.intermediateBuildFilesPath/UninstalledProducts/iphoneos/CombineFirebase.framework':`
