### ISSUE TITLE
Does this Library remove listeners automatically?

### ISSUE THREAD

**Issue by otymartin** [rever-ai/CombineFirebase#22]
@kshivang 

[According to the Firebase docs](https://firebase.google.com/docs/firestore/query-data/listen)
```
When you are no longer interested in listening to query realtime updates, you must detach your listener so that event callbacks stop. This allows the client to stop using bandwidth to receive updates. 
```

So I'm curious how is it that `CombineFirebase` handles this as I can't find any code referencing the removal or detachment of these listeners. I'm concerned with bandwidth usage which can get expensive.

Is `CombineFirebase` doing this automatically somehow or are we responsible for it?

**Comment by kshivang** [comment]
CombineFirebase is exactly for this. Purpose of combineFirebase is to give firebase listener api lifecycle of a [publisher](https://developer.apple.com/documentation/combine/publisher), which should be the default lifecycle for any api in new [Combine Framework paradigm](https://developer.apple.com/documentation/combine). Default lifecycle of a publisher is data is being listened after at-least one subscriber is subscribed, this is done via [sink](https://developer.apple.com/documentation/combine/fail/sink(receivevalue:)) and [assign](https://developer.apple.com/documentation/combine/fail/assign(to:on:)) api. Both sink and assign api in turn return [Cancelable](https://developer.apple.com/documentation/combine/cancellable), which you can use to stop listener by using [cancel()](https://developer.apple.com/documentation/combine/cancellable/cancel()) method of cancellable. Basically all the api of combineFirebase remove listeners on cancel method invocation. Hope that answer your concern.

**Comment by otymartin** [comment]
@kshivang Ahh very informative piece. I always store in my cancelbag because compiler demands it, didn't care to understand it until now.

I saw `cancel()` method in your code but couldn't figure out why it wasnt called but I see it in the `Cancellable` protocol.

Thanks very educational explanation.
