### ISSUE TITLE
What is the CombineFirebase for?

### ISSUE THREAD

**Issue by anoels** [rever-ai/CombineFirebase#4]
It would be much better if you could add a piece of summarized information for people who are new on coding like me. Thank you.

**Comment by kshivang** [comment]
CombineFirebase is better way to use [Firebase iOS SDK](https://github.com/firebase/firebase-ios-sdk) in swiftUI, by providing [combine](https://developer.apple.com/documentation/combine) api to firebases sdk. To learn more about firebase you can visit [link](https://firebase.google.com).

Sorry for the late response.

**Comment by anoels** [comment]
Thank you, Kshivang.

I am going to read the documents to learn more about the combination
