### ISSUE TITLE
Is it possible to paginate data with CombineFirebase?

### ISSUE THREAD

**Issue by anoels** [rever-ai/CombineFirebase#6]
I would like to know if it is possible to paginate data and how to achieve it.

Thank you

**Comment by kshivang** [comment]
Sorry for late response. You can achieve that using using firestore .startWith or .startAt with .limit.
[firebase docs](https://firebase.google.com/docs/firestore/query-data/query-cursors#swift) and at last append .publisher to use it as swiftui-combine compatible api. You have use different publisher for every page. To know end of page you can add .onApper swiftUI with every element of list.

**Comment by anoels** [comment]
Thank you very much. I am gonna try as you said.
